#!/usr/bin/env bash
# Migrate old per-agent volumes into the new single-volume profile layout.
# Usage: migrate-volumes.sh <volumes_root> <target_agent_dir>
#   volumes_root  dir containing agent-main, agent-researcher, agent-simple, agent-coder
#   target        the new ./volumes/agent directory (created if missing)
# Old volumes are NEVER modified — they remain as backup.
# Only state worth carrying across versions is copied: memories/, cron/, workspace/.
# config.yaml, SOUL.md, skills, state.db, sessions are NOT copied (incompatible
# or regenerated by bootstrap).
set -euo pipefail

SRC_ROOT="${1:?usage: migrate-volumes.sh <volumes_root> <target_agent_dir>}"
TARGET="${2:?usage: migrate-volumes.sh <volumes_root> <target_agent_dir>}"

CARRY_DIRS=(memories cron workspace)

copy_carry() { # <src_profile_dir> <dst_dir>
  local src="$1" dst="$2" d
  for d in "${CARRY_DIRS[@]}"; do
    if [ -d "$src/$d" ]; then
      mkdir -p "$dst"
      cp -rn "$src/$d" "$dst/" 2>/dev/null || true   # -n: never overwrite
    fi
  done
}

main_src="$SRC_ROOT/agent-main"
if [ -d "$main_src" ]; then
  mkdir -p "$TARGET"
  copy_carry "$main_src" "$TARGET"
  echo "[migrate] main -> $TARGET"
fi

for name in researcher simple coder; do
  src="$SRC_ROOT/agent-$name"
  if [ -d "$src" ]; then
    copy_carry "$src" "$TARGET/profiles/$name"
    echo "[migrate] $name -> $TARGET/profiles/$name"
  fi
done

echo "[migrate] done. Old volumes left untouched in $SRC_ROOT"