#!/usr/bin/env bash
# Migrate old per-agent volumes into the new single-volume profile layout.
# Usage: migrate-volumes.sh <volumes_root> <target_agent_dir>
#   volumes_root  dir containing agent-main, agent-researcher, agent-simple, agent-coder
#   target        the new ./volumes/agent directory (created if missing)
# Old volumes are NEVER modified — they remain as backup.
# Only state worth carrying across versions is copied: memories/, cron/, workspace/.
# config.yaml, SOUL.md, skills, state.db, sessions are NOT copied (incompatible
# or regenerated by bootstrap).
# cp -Rn: -R (NOT -r) so symlinks are preserved on macOS (BSD) as on Linux (GNU);
# -n so existing files are never overwritten.
set -euo pipefail

SRC_ROOT="${1:?usage: migrate-volumes.sh <volumes_root> <target_agent_dir>}"
TARGET="${2:?usage: migrate-volumes.sh <volumes_root> <target_agent_dir>}"

if [ ! -d "$SRC_ROOT" ]; then
  echo "[migrate] ERROR: volumes_root '$SRC_ROOT' is not a directory" >&2
  exit 1
fi
found_any=0
for name in main researcher simple coder; do
  if [ -d "$SRC_ROOT/agent-$name" ]; then found_any=1; fi
done
if [ "$found_any" -ne 1 ]; then
  echo "[migrate] ERROR: no agent-main/agent-researcher/agent-simple/agent-coder dirs under '$SRC_ROOT' — is the argument order right?" >&2
  exit 1
fi

CARRY_DIRS=(memories cron workspace)

copy_carry() { # <src_profile_dir> <dst_dir>
  local src="$1" dst="$2" d attempted=0
  for d in "${CARRY_DIRS[@]}"; do
    if [ -d "$src/$d" ]; then
      attempted=1
      mkdir -p "$dst"
      if cp -Rn "$src/$d" "$dst/"; then
        echo "[migrate]   copied $src/$d -> $dst/"
      else
        echo "[migrate] WARNING: $src/$d was not fully copied — check errors above" >&2
      fi
    fi
  done
  [ "$attempted" -eq 1 ]
}

main_src="$SRC_ROOT/agent-main"
if [ -d "$main_src" ]; then
  mkdir -p "$TARGET"
  if copy_carry "$main_src" "$TARGET"; then
    echo "[migrate] main -> $TARGET"
  else
    echo "[migrate] main: nothing to copy in $main_src"
  fi
fi

for name in researcher simple coder; do
  src="$SRC_ROOT/agent-$name"
  if [ -d "$src" ]; then
    if copy_carry "$src" "$TARGET/profiles/$name"; then
      echo "[migrate] $name -> $TARGET/profiles/$name"
    else
      echo "[migrate] $name: nothing to copy in $src"
    fi
  fi
done

echo "[migrate] done. Old volumes left untouched in $SRC_ROOT"