/**
 * Document Creation Skill Implementation
 * Creates documents in various formats with customizable templates
 * Uses pdfmake for PDF generation with table support
 */

import PdfPrinter = require('pdfmake');
import { writeFileSync, mkdirSync, existsSync } from 'fs';
import { dirname } from 'path';

// Define fonts for pdfmake
const fonts = {
  Helvetica: {
    normal: 'Helvetica',
    bold: 'Helvetica-Bold',
    italics: 'Helvetica-Oblique',
    bolditalics: 'Helvetica-BoldOblique'
  }
};

interface TableData {
  headers: string[];
  rows: string[][];
  widths?: Array<number | string>;
}

interface DocumentParams {
  format: 'pdf' | 'docx';
  template: 'report' | 'article' | 'analysis' | 'letter' | 'custom';
  language: 'en' | 'pl';
  content: {
    title: string;
    author?: string;
    date?: string;
    sections: Array<{
      heading: string;
      content: string;
      subsections?: Array<{
        heading: string;
        content: string;
      }>;
      tables?: Array<TableData>;
    }>;
  };
  output?: {
    filename?: string;
    directory?: string;
  };
}

interface DocumentResult {
  success: boolean;
  filePath: string;
  fileName: string;
  fileSize: number;
  format: string;
  createdAt: string;
}

// Template styles for different document types
const templateStyles: Record<string, Record<string, any>> = {
  report: {
    headerStyle: { fontSize: 24, bold: true, margin: [0, 0, 0, 20] as [number, number, number, number] },
    subheaderStyle: { fontSize: 16, bold: true, margin: [0, 15, 0, 10] as [number, number, number, number] },
    subsubsectionStyle: { fontSize: 14, bold: true, margin: [0, 10, 0, 8] as [number, number, number, number] },
    bodyStyle: { fontSize: 11, margin: [0, 0, 0, 10] as [number, number, number, number] },
    metadataStyle: { fontSize: 10, italics: true, margin: [0, 0, 0, 15] as [number, number, number, number] }
  },
  article: {
    headerStyle: { fontSize: 22, bold: true, margin: [0, 0, 0, 15] as [number, number, number, number] },
    subheaderStyle: { fontSize: 16, bold: true, margin: [0, 15, 0, 10] as [number, number, number, number] },
    subsubsectionStyle: { fontSize: 13, bold: true, margin: [0, 10, 0, 8] as [number, number, number, number] },
    bodyStyle: { fontSize: 11, margin: [0, 0, 0, 10] as [number, number, number, number] },
    metadataStyle: { fontSize: 10, italics: true, margin: [0, 0, 0, 20] as [number, number, number, number] }
  },
  analysis: {
    headerStyle: { fontSize: 22, bold: true, margin: [0, 0, 0, 10] as [number, number, number, number] },
    subheaderStyle: { fontSize: 16, bold: true, margin: [0, 15, 0, 10] as [number, number, number, number] },
    subsubsectionStyle: { fontSize: 14, bold: true, margin: [0, 10, 0, 8] as [number, number, number, number] },
    bodyStyle: { fontSize: 11, margin: [0, 0, 0, 10] as [number, number, number, number] },
    metadataStyle: { fontSize: 10, margin: [0, 0, 0, 15] as [number, number, number, number] }
  },
  letter: {
    headerStyle: { fontSize: 14, bold: true, margin: [0, 0, 0, 10] as [number, number, number, number] },
    subheaderStyle: { fontSize: 12, bold: true, margin: [0, 10, 0, 8] as [number, number, number, number] },
    subsubsectionStyle: { fontSize: 11, bold: true, margin: [0, 8, 0, 6] as [number, number, number, number] },
    bodyStyle: { fontSize: 11, margin: [0, 0, 0, 8] as [number, number, number, number] },
    metadataStyle: { fontSize: 10, margin: [0, 0, 0, 15] as [number, number, number, number] }
  },
  custom: {
    headerStyle: { fontSize: 20, bold: true, margin: [0, 0, 0, 15] as [number, number, number, number] },
    subheaderStyle: { fontSize: 15, bold: true, margin: [0, 12, 0, 8] as [number, number, number, number] },
    subsubsectionStyle: { fontSize: 13, bold: true, margin: [0, 10, 0, 6] as [number, number, number, number] },
    bodyStyle: { fontSize: 11, margin: [0, 0, 0, 10] as [number, number, number, number] },
    metadataStyle: { fontSize: 10, margin: [0, 0, 0, 15] as [number, number, number, number] }
  }
};

// Language-specific labels
const labels: Record<string, Record<string, string>> = {
  en: {
    author: 'Author',
    date: 'Date',
    generated: 'Generated by Mini Agent',
    analysisReport: 'Analysis Report',
    preparedBy: 'Prepared by'
  },
  pl: {
    author: 'Autor',
    date: 'Data',
    generated: 'Wygenerowane przez Mini Agent',
    analysisReport: 'Raport Analityczny',
    preparedBy: 'Przygotowane przez'
  }
};

/**
 * Build content array for pdfmake from document parameters
 */
function buildContent(params: DocumentParams): any[] {
  const { template, language, content } = params;
  const styles = templateStyles[template] || templateStyles.custom;
  const lang = labels[language] || labels.en;
  const docContent: any[] = [];

  // Title
  docContent.push({
    text: content.title,
    style: 'header'
  });

  // Metadata (author and date)
  const author = content.author || 'Mini Agent';
  const date = content.date || new Date().toISOString().split('T')[0];

  if (template === 'report') {
    docContent.push({
      text: [
        { text: `${lang.author}: `, bold: true },
        { text: author },
        { text: '\n' },
        { text: `${lang.date}: `, bold: true },
        { text: date }
      ],
      style: 'metadata'
    });
  } else if (template === 'article') {
    docContent.push({
      text: `By ${author}`,
      style: 'metadata',
      italics: true
    });
  } else if (template === 'analysis') {
    docContent.push({
      text: [
        { text: `${lang.analysisReport}\n\n`, bold: true },
        { text: `${lang.preparedBy}: `, bold: true },
        { text: author },
        { text: '\n' },
        { text: `${lang.date}: `, bold: true },
        { text: date }
      ],
      style: 'metadata'
    });
  } else if (template === 'letter') {
    docContent.push({
      text: date,
      style: 'metadata'
    });
  }

  // Sections
  for (const section of content.sections) {
    // Section heading (skip for letter template if empty)
    if (section.heading && (template !== 'letter' || section.heading)) {
      docContent.push({
        text: section.heading,
        style: 'subheader'
      });
    }

    // Section content
    if (section.content) {
      docContent.push({
        text: section.content,
        style: 'body'
      });
    }

    // Tables in section
    if (section.tables && section.tables.length > 0) {
      for (const table of section.tables) {
        const tableContent = buildTable(table);
        docContent.push(tableContent);
      }
    }

    // Subsections
    if (section.subsections) {
      for (const sub of section.subsections) {
        docContent.push({
          text: sub.heading,
          style: 'subsubsection'
        });
        if (sub.content) {
          docContent.push({
            text: sub.content,
            style: 'body'
          });
        }
      }
    }
  }

  // Footer for letter template
  if (template === 'letter' && content.author) {
    docContent.push({
      text: '\n\nSincerely,\n' + content.author,
      style: 'body'
    });
  }

  // Footer for analysis template
  if (template === 'analysis') {
    docContent.push({
      text: '\n\n---\n\n*This analysis was generated automatically.*',
      style: 'body'
    });
  }

  return docContent;
}

/**
 * Build a pdfmake table definition
 */
function buildTable(table: TableData): any {
  const columnWidths = table.widths || table.headers.map(() => '*');

  return {
    table: {
      headerRows: 1,
      widths: columnWidths,
      body: [
        // Header row with styling
        table.headers.map((header) => ({
          text: header,
          bold: true,
          fillColor: '#EEEEEE'
        })),
        // Data rows
        ...table.rows.map((row) =>
          row.map((cell) => ({ text: cell || '' }))
        )
      ]
    },
    layout: {
      hLineWidth: () => 1,
      vLineWidth: () => 1,
      hLineColor: () => '#CCCCCC',
      vLineColor: () => '#CCCCCC',
      paddingLeft: () => 6,
      paddingRight: () => 6,
      paddingTop: () => 4,
      paddingBottom: () => 4
    },
    margin: [0, 10, 0, 10] as [number, number, number, number]
  };
}

/**
 * Create PDF using pdfmake
 */
async function createPdf(params: DocumentParams): Promise<Buffer> {
  const printer = new PdfPrinter(fonts);

  const docDefinition = {
    content: buildContent(params),
    styles: {
      header: templateStyles[params.template]?.headerStyle || templateStyles.custom.headerStyle,
      subheader: templateStyles[params.template]?.subheaderStyle || templateStyles.custom.subheaderStyle,
      subsubsection: templateStyles[params.template]?.subsubsectionStyle || templateStyles.custom.subsubsectionStyle,
      body: templateStyles[params.template]?.bodyStyle || templateStyles.custom.bodyStyle,
      metadata: templateStyles[params.template]?.metadataStyle || templateStyles.custom.metadataStyle
    },
    defaultStyle: {
      font: 'Helvetica'
    },
    pageSize: 'A4' as const,
    pageMargins: [50, 50, 50, 50] as [number, number, number, number]
  };

  return new Promise((resolve, reject) => {
    try {
      const pdfDoc = printer.createPdfKitDocument(docDefinition);

      const chunks: Buffer[] = [];
      pdfDoc.on('data', (chunk: Buffer) => {
        chunks.push(chunk);
      });

      pdfDoc.on('end', () => {
        resolve(Buffer.concat(chunks));
      });

      pdfDoc.on('error', (err: Error) => {
        reject(err);
      });

      pdfDoc.end();
    } catch (err) {
      reject(err);
    }
  });
}

/**
 * Create DOCX (placeholder - requires docx library)
 */
async function createDocx(markdown: string, params: DocumentParams): Promise<Buffer> {
  // In production, use docx library
  // For now, return placeholder
  console.log('DOCX generation requires docx library');

  const content = `[DOCX Document]\n\n${markdown}\n\n[End of DOCX]`;
  return Buffer.from(content, 'utf-8');
}

/**
 * Main function to create documents
 */
export async function documentCreation(params: DocumentParams): Promise<DocumentResult> {
  const {
    format,
    template,
    language,
    content,
    output = {}
  } = params;

  const resultsDir = output.directory || '/app/results';
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
  const fileName = output.filename || `${content.title.replace(/[^a-zA-Z0-9]/g, '_')}_${timestamp}`;
  const fileExt = format === 'pdf' ? 'pdf' : 'docx';
  const filePath = `${resultsDir}/${fileName}.${fileExt}`;

  try {
    // Ensure output directory exists
    const dir = dirname(filePath);
    if (!existsSync(dir)) {
      mkdirSync(dir, { recursive: true });
    }

    // Create document in requested format
    let buffer: Buffer;
    if (format === 'pdf') {
      buffer = await createPdf(params);
    } else {
      const markdown = ''; // generateMarkdown(params) - no longer needed for PDF
      buffer = await createDocx(markdown, params);
    }

    // Write file to disk
    writeFileSync(filePath, buffer);

    console.log(`Document created: ${filePath}`);
    console.log(`Content length: ${buffer.length} bytes`);

    return {
      success: true,
      filePath,
      fileName: `${fileName}.${fileExt}`,
      fileSize: buffer.length,
      format,
      createdAt: new Date().toISOString()
    };

  } catch (error) {
    throw new Error(`Document creation failed: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
}

export default documentCreation;