/**
 * Document Creation Skill Implementation
 * Creates documents in various formats with customizable templates
 */

interface DocumentParams {
  format: 'pdf' | 'docx';
  template: 'report' | 'article' | 'analysis' | 'letter' | 'custom';
  language: 'en' | 'pl';
  content: {
    title: string;
    author?: string;
    date?: string;
    sections: Array<{
      heading: string;
      content: string;
      subsections?: Array<{
        heading: string;
        content: string;
      }>;
    }>;
  };
  output?: {
    filename?: string;
    directory?: string;
  };
}

interface DocumentResult {
  success: boolean;
  filePath: string;
  fileName: string;
  fileSize: number;
  format: string;
  createdAt: string;
}

// Template definitions
const templates = {
  report: {
    en: {
      headerTemplate: '# {title}\n\n**Author:** {author}\n**Date:** {date}\n\n---\n\n',
      sectionTemplate: '## {heading}\n\n{content}\n\n',
      subsectionTemplate: '### {heading}\n\n{content}\n\n',
      footerTemplate: '\n\n---\n\n*Generated by Mini Agent*'
    },
    pl: {
      headerTemplate: '# {title}\n\n**Autor:** {author}\n**Data:** {date}\n\n---\n\n',
      sectionTemplate: '## {heading}\n\n{content}\n\n',
      subsectionTemplate: '### {heading}\n\n{content}\n\n',
      footerTemplate: '\n\n---\n\n*Wygenerowane przez Mini Agent*'
    }
  },
  article: {
    en: {
      headerTemplate: '# {title}\n\n*By {author}*\n\n',
      sectionTemplate: '\n## {heading}\n\n{content}\n\n',
      subsectionTemplate: '\n### {heading}\n\n{content}\n\n',
      footerTemplate: ''
    },
    pl: {
      headerTemplate: '# {title}\n\n*Przez {author}*\n\n',
      sectionTemplate: '\n## {heading}\n\n{content}\n\n',
      subsectionTemplate: '\n### {heading}\n\n{content}\n\n',
      footerTemplate: ''
    }
  },
  analysis: {
    en: {
      headerTemplate: '# {title}\n\n**Analysis Report**\n\n**Prepared by:** {author}\n**Date:** {date}\n\n',
      sectionTemplate: '## {heading}\n\n{content}\n\n',
      subsectionTemplate: '### {heading}\n\n{content}\n\n',
      footerTemplate: '\n\n---\n\n*This analysis was generated automatically.*'
    },
    pl: {
      headerTemplate: '# {title}\n\n**Raport Analityczny**\n\n**Przygotowane przez:** {author}\n**Data:** {date}\n\n',
      sectionTemplate: '## {heading}\n\n{content}\n\n',
      subsectionTemplate: '### {heading}\n\n{content}\n\n',
      footerTemplate: '\n\n---\n\n*Ta analiza została wygenerowana automatycznie.*'
    }
  },
  letter: {
    en: {
      headerTemplate: '{title}\n\n{date}\n\n',
      sectionTemplate: '{heading}\n\n{content}\n\n',
      subsectionTemplate: '',
      footerTemplate: '\n\nSincerely,\n{author}'
    },
    pl: {
      headerTemplate: '{title}\n\n{date}\n\n',
      sectionTemplate: '{heading}\n\n{content}\n\n',
      subsectionTemplate: '',
      footerTemplate: '\n\nZ poważaniem,\n{author}'
    }
  },
  custom: {
    en: {
      headerTemplate: '# {title}\n\n',
      sectionTemplate: '## {heading}\n\n{content}\n\n',
      subsectionTemplate: '### {heading}\n\n{content}\n\n',
      footerTemplate: ''
    },
    pl: {
      headerTemplate: '# {title}\n\n',
      sectionTemplate: '## {heading}\n\n{content}\n\n',
      subsectionTemplate: '### {heading}\n\n{content}\n\n',
      footerTemplate: ''
    }
  }
};

// Generate markdown content
function generateMarkdown(params: DocumentParams): string {
  const { format, template, language, content } = params;
  const templateDef = templates[template][language];
  const date = content.date || new Date().toISOString().split('T')[0];
  const author = content.author || 'Mini Agent';

  let markdown = templateDef.headerTemplate
    .replace('{title}', content.title)
    .replace('{author}', author)
    .replace('{date}', date);

  for (const section of content.sections) {
    markdown += templateDef.sectionTemplate
      .replace('{heading}', section.heading)
      .replace('{content}', section.content);

    if (section.subsections) {
      for (const sub of section.subsections) {
        markdown += templateDef.subsectionTemplate
          .replace('{heading}', sub.heading)
          .replace('{content}', sub.content);
      }
    }
  }

  markdown += templateDef.footerTemplate.replace('{author}', author);

  return markdown;
}

// Create PDF (placeholder - requires pdfkit in production)
async function createPdf(markdown: string, params: DocumentParams): Promise<Buffer> {
  // In production, use pdfkit or similar library
  // For now, return placeholder
  console.log('PDF generation requires pdfkit library');

  const content = `[PDF Document]\n\n${markdown}\n\n[End of PDF]`;
  return Buffer.from(content, 'utf-8');
}

// Create DOCX (placeholder - requires docx library in production)
async function createDocx(markdown: string, params: DocumentParams): Promise<Buffer> {
  // In production, use docx library
  // For now, return placeholder
  console.log('DOCX generation requires docx library');

  const content = `[DOCX Document]\n\n${markdown}\n\n[End of DOCX]`;
  return Buffer.from(content, 'utf-8');
}

// Main function
export async function documentCreation(params: DocumentParams): Promise<DocumentResult> {
  const {
    format,
    template,
    language,
    content,
    output = {}
  } = params;

  const startTime = Date.now();
  const resultsDir = output.directory || '/app/results';
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
  const fileName = output.filename || `${content.title.replace(/[^a-zA-Z0-9]/g, '_')}_${timestamp}`;
  const fileExt = format === 'pdf' ? 'pdf' : 'docx';
  const filePath = `${resultsDir}/${fileName}.${fileExt}`;

  try {
    // Generate markdown content
    const markdown = generateMarkdown(params);

    // Create document in requested format
    let buffer: Buffer;
    if (format === 'pdf') {
      buffer = await createPdf(markdown, params);
    } else {
      buffer = await createDocx(markdown, params);
    }

    // Write to results directory (in production, use fs.writeFile)
    // For now, just return success with file info
    console.log(`Document created: ${filePath}`);
    console.log(`Content length: ${buffer.length} bytes`);

    return {
      success: true,
      filePath,
      fileName: `${fileName}.${fileExt}`,
      fileSize: buffer.length,
      format,
      createdAt: new Date().toISOString()
    };

  } catch (error) {
    throw new Error(`Document creation failed: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
}

export default documentCreation;