FROM nousresearch/hermes-agent:v2026.5.7

# Environment setup
ENV NODE_COMPILE_CACHE=/var/tmp/node-compile-cache

# Create node compile cache directory
RUN mkdir -p /var/tmp/node-compile-cache

# Install additional system dependencies eg. browser
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    systemctl ca-certificates make g++ chromium python3-pip \
    && rm -rf /var/lib/apt/lists/*

# Install NATS Python client
RUN pip3 install --no-cache-dir --break-system-packages nats-py==2.14.0

RUN mkdir -p /app/scripts
COPY ./src/config/ /app/config/
COPY ./src/scripts/ /app/scripts/
COPY ./src/agents/ /app/agents/
COPY ./src/skills/ /app/skills/
RUN chmod +x /app/scripts/*
RUN cd /app/scripts && npm install js-yaml@4.1.1

# Set working directory for skills build
WORKDIR /app/skills

# Install skills dependencies and build skills
RUN npm install 
RUN npm run build

WORKDIR /app

ENTRYPOINT ["scripts/hermes-entrypoint.sh"]
CMD ["bash", "-c", "/usr/bin/tini -g -- /opt/hermes/docker/entrypoint.sh gateway run"]